name: Build Angular App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19'  # updated to use Node.js version 18

    - name: Install dependencies
      run: npm install -f

    - name: Install Angular CLI
      run: npm install -g @angular/cli -f

    - name: Build Angular app
      run: ng build --configuration production
